### ISSUE TITLE
Python: Chain ImportError Bug

### ISSUE THREAD

**Issue by rqnguyen100** [rudolfolah/chaincrafter#9]
I'm trying to run some of the examples and I keep on getting this error.

```python
ImportError: cannot import name 'Chain' from partially initialized module 'chaincrafter' (most likely due to a circular import) (chaincrafter/__init__.py)
```
<br>

<ins>How I reached this point</ins>:
1) Forked and cloned repository onto local machine
2) Pip installed chaincrafter
3) Tried to run ```hello_world.py``` under ./python/examples

<br>

When I run the ```__init__.py``` script, there are no errors. I thought it might be an issue of importing incorrectly. The original import is 
```python
from chaincrafter import Chain, Prompt
```
while in the ```__init__.py``` script, these lines ares used
```python
from chaincrafter.chains import Chain
from chaincrafter.prompts import Prompt
```
still getting the same error nonetheless.

**Comment by rudolfolah** [comment]
I was able to reproduce the issue, the `math.py` example has to be renamed to avoid conflicting with the `math` module.

Once I renamed the `math.py` file `math_example.py`, I was able to run the example with `python examples/hello_world.py` and with `python -m examples.hello_world`

**Comment by rqnguyen100** [comment]
Problem resolved.
